
package trikigame;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class WindowMain extends javax.swing.JFrame {

    public WindowMain() {
        initComponents(); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfMatriz = new javax.swing.JPanel();
        lbl00 = new javax.swing.JLabel();
        lbl01 = new javax.swing.JLabel();
        lbl02 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        jfNames = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        lblO = new javax.swing.JLabel();
        lblNameX = new javax.swing.JLabel();
        lblNameO = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btbPlayAgain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 50));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jfMatriz.setLayout(new java.awt.GridLayout(3, 3));

        lbl00.setBackground(new java.awt.Color(153, 153, 255));
        lbl00.setFont(new java.awt.Font("FreeMono", 1, 48)); // NOI18N
        lbl00.setForeground(new java.awt.Color(0, 0, 51));
        lbl00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl00.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl00.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl00.setOpaque(true);
        lbl00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl00MouseClicked(evt);
            }
        });
        jfMatriz.add(lbl00);

        lbl01.setBackground(new java.awt.Color(153, 153, 255));
        lbl01.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lbl01.setForeground(new java.awt.Color(0, 0, 51));
        lbl01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl01.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl01.setOpaque(true);
        lbl01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl01MouseClicked(evt);
            }
        });
        jfMatriz.add(lbl01);

        lbl02.setBackground(new java.awt.Color(153, 153, 255));
        lbl02.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lbl02.setForeground(new java.awt.Color(0, 0, 51));
        lbl02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl02.setOpaque(true);
        lbl02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl02MouseClicked(evt);
            }
        });
        jfMatriz.add(lbl02);

        lbl10.setBackground(new java.awt.Color(153, 153, 255));
        lbl10.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lbl10.setForeground(new java.awt.Color(0, 0, 51));
        lbl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl10.setOpaque(true);
        lbl10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl10MouseClicked(evt);
            }
        });
        jfMatriz.add(lbl10);

        lbl11.setBackground(new java.awt.Color(153, 153, 255));
        lbl11.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lbl11.setForeground(new java.awt.Color(0, 0, 51));
        lbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl11.setOpaque(true);
        lbl11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl11MouseClicked(evt);
            }
        });
        jfMatriz.add(lbl11);

        lbl12.setBackground(new java.awt.Color(153, 153, 255));
        lbl12.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lbl12.setForeground(new java.awt.Color(0, 0, 51));
        lbl12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl12.setOpaque(true);
        lbl12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl12MouseClicked(evt);
            }
        });
        jfMatriz.add(lbl12);

        lbl20.setBackground(new java.awt.Color(153, 153, 255));
        lbl20.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lbl20.setForeground(new java.awt.Color(0, 0, 51));
        lbl20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl20.setOpaque(true);
        lbl20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl20MouseClicked(evt);
            }
        });
        jfMatriz.add(lbl20);

        lbl21.setBackground(new java.awt.Color(153, 153, 255));
        lbl21.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lbl21.setForeground(new java.awt.Color(0, 0, 51));
        lbl21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl21.setOpaque(true);
        lbl21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl21MouseClicked(evt);
            }
        });
        jfMatriz.add(lbl21);

        lbl22.setBackground(new java.awt.Color(153, 153, 255));
        lbl22.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lbl22.setForeground(new java.awt.Color(0, 0, 51));
        lbl22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl22.setOpaque(true);
        lbl22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl22MouseClicked(evt);
            }
        });
        jfMatriz.add(lbl22);

        lblX.setForeground(new java.awt.Color(0, 0, 204));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("X");
        lblX.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));
        lblX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblO.setForeground(new java.awt.Color(255, 153, 0));
        lblO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblO.setText("O");
        lblO.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));

        lblNameX.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lblNameX.setForeground(new java.awt.Color(0, 102, 0));
        lblNameX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameX.setText("click para asignar nombre...");
        lblNameX.setToolTipText("");
        lblNameX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNameXMouseClicked(evt);
            }
        });
        lblNameX.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblNameXInputMethodTextChanged(evt);
            }
        });

        lblNameO.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lblNameO.setForeground(new java.awt.Color(102, 0, 102));
        lblNameO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameO.setText("click para asignar nombre...");
        lblNameO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNameOMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jfNamesLayout = new javax.swing.GroupLayout(jfNames);
        jfNames.setLayout(jfNamesLayout);
        jfNamesLayout.setHorizontalGroup(
            jfNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfNamesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jfNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblO, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jfNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNameX, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(lblNameO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jfNamesLayout.setVerticalGroup(
            jfNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfNamesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNameX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblX, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jfNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Purisa", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 255, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("THREE IN LINE GAME!");
        lblTitle.setOpaque(true);

        btbPlayAgain.setBackground(new java.awt.Color(0, 102, 0));
        btbPlayAgain.setForeground(new java.awt.Color(102, 255, 102));
        btbPlayAgain.setText("Play Again!");
        btbPlayAgain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbPlayAgainMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jfNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btbPlayAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btbPlayAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jfMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblNameXInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblNameXInputMethodTextChanged
    }//GEN-LAST:event_lblNameXInputMethodTextChanged

    private void lblNameXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameXMouseClicked
        // it lets us to set our names in order to personalize the view.
        Players playerX = new Players();
        playerX.setNameX(JOptionPane.showInputDialog("Nombre para jugador X:"));
        lblNameX.setText(playerX.getNameX());
    }//GEN-LAST:event_lblNameXMouseClicked

    private void lblNameOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameOMouseClicked
        // it lets us to set our names in order to personalize the view.
        Players playerO = new Players();
        playerO.setNameO(JOptionPane.showInputDialog("Nombre para jugador O:"));
        lblNameO.setText(playerO.getNameO());
    }//GEN-LAST:event_lblNameOMouseClicked
    
    //firs label
    private void lbl00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl00MouseClicked
        //each label must call the method where the player will write must 
        Validations game = new Validations();        
        JLabel [] labels = {lbl00, lbl01, lbl02, lbl10, lbl11, lbl12, lbl20, lbl21, lbl22};
        game.checkAllLabels(labels);
        game.setAllNull();        
        game.setTurn(labels);       
        game.checkLabel(lbl00);
        game.checkVictory(labels);
        game.setFinishGame(labels);
        game.setEndGame();        
        if (game.getEndGame()) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        } else if (!game.getEndGame() && game.getNullAccount() == 1) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        }        
    }//GEN-LAST:event_lbl00MouseClicked
     
    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
    }//GEN-LAST:event_formMouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened
    
    //secod label
    private void lbl01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl01MouseClicked
        Validations game = new Validations();
        JLabel [] labels = {lbl00, lbl01, lbl02, lbl10, lbl11, lbl12, lbl20, lbl21, lbl22};
        game.checkAllLabels(labels);
        game.setAllNull();
        game.setTurn(labels);
        game.checkLabel(lbl01);
        game.checkVictory(labels);
        game.setFinishGame(labels);
        game.setEndGame();        
        if (game.getEndGame()) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        } else if (!game.getEndGame() && game.getNullAccount() == 1) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        }        
    }//GEN-LAST:event_lbl01MouseClicked
    
    //thrid label
    private void lbl02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl02MouseClicked
        Validations game = new Validations();
        JLabel [] labels = {lbl00, lbl01, lbl02, lbl10, lbl11, lbl12, lbl20, lbl21, lbl22};
        game.checkAllLabels(labels);
        game.setAllNull();        
        game.setTurn(labels);
        game.checkLabel(lbl02);
        game.checkVictory(labels);
        game.setFinishGame(labels);
        game.setEndGame();        
        if (game.getEndGame()) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        } else if (!game.getEndGame() && game.getNullAccount() == 1) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        }
    }//GEN-LAST:event_lbl02MouseClicked

    //fourth label
    private void lbl10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl10MouseClicked
        Validations game = new Validations();
        JLabel [] labels = {lbl00, lbl01, lbl02, lbl10, lbl11, lbl12, lbl20, lbl21, lbl22};
        game.checkAllLabels(labels);
        game.setAllNull();        
        game.setTurn(labels);
        game.checkLabel(lbl10);
        game.checkVictory(labels);
        game.setFinishGame(labels);
        game.setEndGame();        
        if (game.getEndGame()) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        } else if (!game.getEndGame() && game.getNullAccount() == 1) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        }
    }//GEN-LAST:event_lbl10MouseClicked
    
    //fifth lavel
    private void lbl11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl11MouseClicked
        Validations game = new Validations();
        JLabel [] labels = {lbl00, lbl01, lbl02, lbl10, lbl11, lbl12, lbl20, lbl21, lbl22};
        game.checkAllLabels(labels);
        game.setAllNull();        
        game.setTurn(labels);
        game.checkLabel(lbl11);
        game.checkVictory(labels);
        game.setFinishGame(labels);
        game.setEndGame();        
        if (game.getEndGame()) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        } else if (!game.getEndGame() && game.getNullAccount() == 1) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        }
    }//GEN-LAST:event_lbl11MouseClicked
    
    //sixth label
    private void lbl12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl12MouseClicked
        Validations game = new Validations();
        JLabel [] labels = {lbl00, lbl01, lbl02, lbl10, lbl11, lbl12, lbl20, lbl21, lbl22};
        game.checkAllLabels(labels);
        game.setAllNull();        
        game.setTurn(labels);
        game.checkLabel(lbl12);
        game.checkVictory(labels);
        game.setFinishGame(labels);
        game.setEndGame();        
        if (game.getEndGame()) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        } else if (!game.getEndGame() && game.getNullAccount() == 1) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        }
    }//GEN-LAST:event_lbl12MouseClicked
    
    //seventh label
    private void lbl20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl20MouseClicked
        Validations game = new Validations();
        JLabel [] labels = {lbl00, lbl01, lbl02, lbl10, lbl11, lbl12, lbl20, lbl21, lbl22};
        game.checkAllLabels(labels);
        game.setAllNull();        
        game.setTurn(labels);
        game.checkLabel(lbl20);
        game.checkVictory(labels);
        game.setFinishGame(labels);
        game.setEndGame();        
        if (game.getEndGame()) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        } else if (!game.getEndGame() && game.getNullAccount() == 1) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        }
    }//GEN-LAST:event_lbl20MouseClicked
    
    //eighth label
    private void lbl21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl21MouseClicked
        Validations game = new Validations();
        JLabel [] labels = {lbl00, lbl01, lbl02, lbl10, lbl11, lbl12, lbl20, lbl21, lbl22};
        game.checkAllLabels(labels);
        game.setAllNull();        
        game.setTurn(labels);
        game.checkLabel(lbl21);
        game.checkVictory(labels);
        game.setFinishGame(labels);
        game.setEndGame();        
        if (game.getEndGame()) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        } else if (!game.getEndGame() && game.getNullAccount() == 1) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        }
    }//GEN-LAST:event_lbl21MouseClicked
    
    //nineth label
    private void lbl22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl22MouseClicked
        Validations game = new Validations();
        JLabel [] labels = {lbl00, lbl01, lbl02, lbl10, lbl11, lbl12, lbl20, lbl21, lbl22};
        game.checkAllLabels(labels);
        game.setAllNull();        
        game.setTurn(labels);
        game.checkLabel(lbl22);
        game.checkVictory(labels);
        game.setFinishGame(labels);
        game.setEndGame();        
        if (game.getEndGame()) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        } else if (!game.getEndGame() && game.getNullAccount() == 1) {
            JOptionPane.showMessageDialog(null, game.getFinishGame());
        }
    }//GEN-LAST:event_lbl22MouseClicked
    
    //this event call the method to restart the game again.
    private void btbPlayAgainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbPlayAgainMouseClicked
        Validations game = new Validations();
        JLabel [] labels = {lbl00, lbl01, lbl02, lbl10, lbl11, lbl12, lbl20, lbl21, lbl22};
        game.setPlayAgain(labels);        
    }//GEN-LAST:event_btbPlayAgainMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowMain().setVisible(true);
                new WindowMain().setLocationRelativeTo(null);                
                JOptionPane.showMessageDialog(null, "¡Bienvenido!...Por favor ingresa los nombres de los jugadores.");               
            }
        });        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbPlayAgain;
    private javax.swing.JPanel jfMatriz;
    private javax.swing.JPanel jfNames;
    private javax.swing.JLabel lbl00;
    private javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl02;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lblNameO;
    private javax.swing.JLabel lblNameX;
    private javax.swing.JLabel lblO;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblX;
    // End of variables declaration//GEN-END:variables
}
